#:schema https://starship.rs/config-schema.json

command_timeout = 200

format       = '''$character'''
right_format = '''$all'''

[aws]
disabled = true
symbol   = ' '

[azure]
disabled = true
symbol   = " "

[battery]
disabled = true

[buf]
disabled = true
symbol   = ' '

[bun]
symbol = ' '

[c]
disabled = true
symbol   = ' '

[cpp]
symbol = ' '

[cmake]
disabled = true
symbol   = ' '

[cobol]
disabled = true

[conda]
disabled = true
symbol   = ' '

[crystal]
disabled = true
symbol   = ' '

[daml]
disabled = true

[dart]
symbol = ' '

[deno]
symbol = ' '

[directory]
home_symbol = '󰋜'
read_only   = ' 󰌾'

[direnv]
disabled = false

[docker_context]
disabled = true
symbol   = ' '

[dotnet]
disabled = true

[elixir]
symbol = ' '

[elm]
disabled = true
symbol   = ' '

[fennel]
symbol = ' '

[fortran]
disabled = true
symbol   = ' '

[fossil_branch]
symbol = ' '

[gcloud]
disabled = true
symbol   = ' '

[git_branch]
symbol = ' '

[git_commit]
tag_disabled = false
tag_symbol   = '  '

[golang]
symbol = ' '

[gradle]
symbol = ' '

[guix_shell]
disabled = true
symbol   = ' '

[haskell]
disabled = true
symbol   = ' '

[haxe]
disabled = true
symbol   = ' '

[hg_branch]
disabled = true
symbol   = ' '

[hostname]
format     = '[$ssh_symbol$hostname]($style) '
ssh_symbol = ' '

[java]
symbol = ' '

[julia]
disabled = true
symbol   = ' '

[kotlin]
symbol = ' '

[kubernetes]
disabled = false
symbol   = ' '

[lua]
symbol = ' '

[memory_usage]
symbol = '󰍛 '

[meson]
disabled = true
symbol   = '󰔷 '

[mojo]
disabled = true

[nim]
disabled = true
symbol   = '󰆥 '

[nix_shell]
symbol = ' '

[nodejs]
symbol = ' '

[ocaml]
disabled = true
symbol   = ' '

[odin]
disabled = true

[os.symbols]
Alpaquita        = ' '
Alpine           = ' '
AlmaLinux        = ' '
Amazon           = ' '
Android          = ' '
AOSC             = ' '
Arch             = ' '
Artix            = ' '
CachyOS          = ' '
CentOS           = ' '
Debian           = ' '
DragonFly        = ' '
Elementary       = ' '
Emscripten       = ' '
EndeavourOS      = ' '
Fedora           = ' '
FreeBSD          = ' '
Garuda           = '󰛓 '
Gentoo           = ' '
HardenedBSD      = '󰞌 '
Illumos          = '󰈸 '
Ios              = '󰀷 '
Kali             = ' '
Linux            = ' '
Mabox            = ' '
Macos            = ' '
Manjaro          = ' '
Mariner          = ' '
MidnightBSD      = ' '
Mint             = ' '
NetBSD           = ' '
NixOS            = ' '
Nobara           = ' '
OpenBSD          = '󰈺 '
openSUSE         = ' '
OracleLinux      = '󰌷 '
Pop              = ' '
Raspbian         = ' '
Redhat           = ' '
RedHatEnterprise = ' '
RockyLinux       = ' '
Redox            = '󰀘 '
Solus            = '󰠳 '
SUSE             = ' '
Ubuntu           = ' '
Unknown          = ' '
Void             = ' '
Windows          = '󰍲 '
Zorin            = ' '

[package]
disabled = true
symbol   = '󰏗 '

[perl]
disabled = true
symbol   = ' '

[php]
disabled = true
symbol   = ' '

[pijul_channel]
symbol = ' '

[pixi]
disabled = true
symbol   = '󰏗 '

[purescript]
disabled = true

[python]
symbol = ' '

[quarto]
disabled = true

[rlang]
disabled = true
symbol   = '󰟔 '

[raku]
disabled = true

[red]
disabled = true

[ruby]
symbol = ' '

[rust]
symbol = '󱘗 '

[scala]
symbol = ' '

[singularity]
disabled = true

[solidity]
disabled = true

[spack]
disabled = true

[status]
symbol = ' '

[sudo]
disabled = false

[swift]
disabled = true
symbol   = ' '

[terraform]
symbol = ' '

[vagrant]
disabled = true

[vlang]
disabled = true

[vcsh]
disabled = true

[xmake]
disabled = true
symbol   = ' '

[zig]
disabled = true
symbol   = ' '
