{{ define "archive" }}
  type            = 'archive'
  exact           = true
  refreshPeriod   = '24h'
  stripComponents = 1
{{ end }}

['.oh-my-zsh']
  {{ template "archive" }}
  url = 'https://codeload.github.com/ohmyzsh/ohmyzsh/tar.gz/refs/heads/master'

['.oh-my-zsh/custom/plugins/zsh-autosuggestions']
  {{ template "archive" }}
  url = 'https://codeload.github.com/zsh-users/zsh-autosuggestions/tar.gz/refs/heads/master'

['.oh-my-zsh/custom/plugins/zsh-syntax-highlighting']
  {{ template "archive" }}
  url = 'https://codeload.github.com/zsh-users/zsh-syntax-highlighting/tar.gz/refs/heads/master'
