{{ define "archive" }}
  type = "archive"
  stripComponents = 1
  refreshPeriod = "24h"
{{ end }}

[".oh-my-zsh"]
  {{ template "archive" }}
  url = "https://codeload.github.com/ohmyzsh/ohmyzsh/tar.gz/refs/heads/master"
  exact = false

[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
  {{ template "archive" }}
  url = "https://codeload.github.com/zsh-users/zsh-autosuggestions/tar.gz/refs/heads/master"
  exact = true

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
  {{ template "archive" }}
  url = "https://codeload.github.com/zsh-users/zsh-syntax-highlighting/tar.gz/refs/heads/master"
  exact = true
