local parsers = {
    'astro',
    'bash',
    'c',
    'comment',
    'cpp',
    'css',
    'csv',
    'cue',
    'dart',
    'diff',
    'dockerfile',
    'ebnf',
    'fennel',
    'fish',
    'git_config',
    'git_rebase',
    'gitattributes',
    'gitcommit',
    'gitignore',
    'go',
    'gomod',
    'gosum',
    'gowork',
    'hcl',
    'hjson',
    'hocon',
    'html',
    'htmldjango',
    'http',
    'ini',
    'java',
    'javascript',
    'jq',
    'jsdoc',
    'json',
    'json5',
    'jsonc',
    'jsonnet',
    'kdl',
    'kotlin',
    'lalrpop',
    'latex',
    'lua',
    'luadoc',
    'make',
    'markdown',
    'markdown_inline',
    'mermaid',
    'nix',
    'org',
    'po',
    'prisma',
    'promql',
    'proto',
    'pug',
    'pymanifest',
    'python',
    'query',
    'racket',
    'regex',
    'requirements',
    'ron',
    'rst',
    'ruby',
    'rust',
    'scala',
    'scss',
    'sql',
    'ssh_config',
    'starlark',
    'strace',
    'svelte',
    'teal',
    'terraform',
    'textproto',
    'thrift',
    'todotxt',
    'toml',
    'tsv',
    'tsx',
    'typescript',
    'vim',
    'vimdoc',
    'vue',
    'xml',
    'yaml',
}

return {
    'nvim-treesitter/nvim-treesitter',
    build = ':TSUpdate',
    opts = {
        ensure_installed = parsers,
        auto_install = true,
        highlight = { enable = true },
        incremental_selection = { enable = true },
        indent = { enable = true },
        rainbow = { enable = true },
    },
    config = function(_, opts)
        require('nvim-treesitter.configs').setup(opts)

        vim.opt.foldmethod = 'expr'
        vim.opt.foldexpr = 'nvim_treesitter#foldexpr()'
        vim.opt.foldenable = false
    end,
}
