# Smart enter (open file or enter dir)
[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter dir or open file"

[[mgr.prepend_keymap]]
on   = "<Right>"
run  = "plugin smart-enter"
desc = "Enter dir or open file"

# Shell
[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = 'shell "$SHELL" --block'
desc = "Open shell here"

# jjui
[[mgr.prepend_keymap]]
on   = ["g", "j"]
run  = "plugin jjui"
desc = "Open jjui"

# Git root
[[mgr.prepend_keymap]]
on   = ["g", "r"]
run  = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "Go to git root"

# Clipboard
[[mgr.prepend_keymap]]
on   = "Y"
run  = "plugin clipboard -- --action=copy"
desc = "Copy files to clipboard"

[[mgr.prepend_keymap]]
on   = "<C-p>"
run  = "plugin clipboard -- --action=paste"
desc = "Paste files from clipboard"

# Diff
[[mgr.prepend_keymap]]
on   = "<C-d>"
run  = "plugin diff"
desc = "Diff selected with hovered"

# Toggle pane
[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore preview"

[[mgr.prepend_keymap]]
on   = "E"
run  = "plugin toggle-pane min-preview"
desc = "Hide or restore preview"

# chmod
[[mgr.prepend_keymap]]
on   = ["c", "m"]
run  = "plugin chmod"
desc = "Chmod on selected files"

# sudo cp/mv
[[mgr.prepend_keymap]]
on   = ["R", "p", "p"]
run  = "plugin sudo -- paste"
desc = "sudo paste"

# sudo cp/mv --force
[[mgr.prepend_keymap]]
on   = ["R", "P"]
run  = "plugin sudo -- paste --force"
desc = "sudo paste --force"

# sudo mv
[[mgr.prepend_keymap]]
on   = ["R", "r"]
run  = "plugin sudo -- rename"
desc = "sudo rename"

# sudo ln -s (absolute-path)
[[mgr.prepend_keymap]]
on   = ["R", "p", "l"]
run  = "plugin sudo -- link"
desc = "sudo link"

# sudo ln -s (relative-path)
[[mgr.prepend_keymap]]
on   = ["R", "p", "r"]
run  = "plugin sudo -- link --relative"
desc = "sudo link (relative)"

# sudo ln
[[mgr.prepend_keymap]]
on   = ["R", "p", "L"]
run  = "plugin sudo -- hardlink"
desc = "sudo hardlink"

# sudo touch/mkdir
[[mgr.prepend_keymap]]
on   = ["R", "a"]
run  = "plugin sudo -- create"
desc = "sudo create"

# sudo trash
[[mgr.prepend_keymap]]
on   = ["R", "d"]
run  = "plugin sudo -- remove"
desc = "sudo trash"

# sudo delete
[[mgr.prepend_keymap]]
on   = ["R", "D"]
run  = "plugin sudo -- remove --permanently"
desc = "sudo delete"
