#!/bin/bash

CONFIG_DIR="${CONFIG_DIR:-$HOME/.config/sketchybar}"
source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/icons.sh"

ITEM_DIR="$CONFIG_DIR/items"
PLUGIN_DIR="$CONFIG_DIR/plugins"

FONT="SF Pro"
ICON_FONT="VictorMono Nerd Font"
PADDINGS=3

PILL_COLOR=0x00000000
PILL_BORDER=0x00000000
PILL_RADIUS=10
PILL_HEIGHT=30
GAP_WIDTH=6

bar=(
	position=top
	height=36
	margin=8
	y_offset=8
	corner_radius=0
	color=$TRANSPARENT
	border_width=0
	sticky=on
	padding_right=10
	padding_left=10
	blur_radius=30
	font_smoothing=on
	shadow=off
	notch_width=188
)
sketchybar --bar "${bar[@]}"

defaults=(
	updates=when_shown
	icon.font="$ICON_FONT:Regular:15.0"
	icon.color=$ICON_COLOR
	icon.padding_left=$PADDINGS
	icon.padding_right=$PADDINGS
	label.font="$FONT:Bold:13.0"
	label.color=$LABEL_COLOR
	label.padding_left=$PADDINGS
	label.padding_right=$PADDINGS
	padding_right=$PADDINGS
	padding_left=$PADDINGS
	scroll_texts=off
)
sketchybar --default "${defaults[@]}"

sketchybar --add event aerospace_workspace_change

source "$ITEM_DIR/spaces.sh"

sketchybar --add item gap_l1 left \
	--set gap_l1 width=$GAP_WIDTH icon.drawing=off label.drawing=off \
	padding_left=0 padding_right=0

source "$ITEM_DIR/front_app.sh"

source "$ITEM_DIR/clock.sh"

sketchybar --add item gap_r1 right \
	--set gap_r1 width=$GAP_WIDTH icon.drawing=off label.drawing=off \
	padding_left=0 padding_right=0

source "$ITEM_DIR/battery.sh"

sketchybar --add item gap_r2 right \
	--set gap_r2 width=$GAP_WIDTH icon.drawing=off label.drawing=off \
	padding_left=0 padding_right=0

source "$ITEM_DIR/volume.sh"

sketchybar --add item gap_r3 right \
	--set gap_r3 width=$GAP_WIDTH icon.drawing=off label.drawing=off \
	padding_left=0 padding_right=0

source "$ITEM_DIR/wifi.sh"

sketchybar --add item gap_r4 right \
	--set gap_r4 width=$GAP_WIDTH icon.drawing=off label.drawing=off \
	padding_left=0 padding_right=0

source "$ITEM_DIR/calendar.sh"

sketchybar --add item gap_r5 right \
	--set gap_r5 width=$GAP_WIDTH icon.drawing=off label.drawing=off \
	padding_left=0 padding_right=0

source "$ITEM_DIR/now_playing.sh"

SPACE_ITEMS=()
for sid in 1 2 3 4 5 6 7 8 9 10; do
	SPACE_ITEMS+=("space.$sid" "space.sep.$sid")
done

sketchybar --add bracket pill_spaces "${SPACE_ITEMS[@]}" \
	--set pill_spaces \
	background.drawing=on \
	background.color=$PILL_COLOR \
	background.corner_radius=$PILL_RADIUS \
	background.border_width=1 \
	background.border_color=$PILL_BORDER \
	background.height=$PILL_HEIGHT

sketchybar --add bracket pill_app front_app \
	--set pill_app \
	background.drawing=on \
	background.color=$PILL_COLOR \
	background.corner_radius=$PILL_RADIUS \
	background.border_width=1 \
	background.border_color=$PILL_BORDER \
	background.height=$PILL_HEIGHT

sketchybar --add bracket pill_wifi wifi \
	--set pill_wifi \
	background.drawing=on \
	background.color=$PILL_COLOR \
	background.corner_radius=$PILL_RADIUS \
	background.border_width=1 \
	background.border_color=$PILL_BORDER \
	background.height=$PILL_HEIGHT

sketchybar --add bracket pill_volume volume \
	--set pill_volume \
	background.drawing=on \
	background.color=$PILL_COLOR \
	background.corner_radius=$PILL_RADIUS \
	background.border_width=1 \
	background.border_color=$PILL_BORDER \
	background.height=$PILL_HEIGHT

sketchybar --add bracket pill_battery battery \
	--set pill_battery \
	background.drawing=on \
	background.color=$PILL_COLOR \
	background.corner_radius=$PILL_RADIUS \
	background.border_width=1 \
	background.border_color=$PILL_BORDER \
	background.height=$PILL_HEIGHT

sketchybar --add bracket pill_calendar calendar \
	--set pill_calendar \
	background.drawing=on \
	background.color=$PILL_COLOR \
	background.corner_radius=$PILL_RADIUS \
	background.border_width=1 \
	background.border_color=$PILL_BORDER \
	background.height=$PILL_HEIGHT

sketchybar --add bracket pill_now_playing now_playing \
	--set pill_now_playing \
	background.drawing=on \
	background.color=$PILL_COLOR \
	background.corner_radius=$PILL_RADIUS \
	background.border_width=1 \
	background.border_color=$PILL_BORDER \
	background.height=$PILL_HEIGHT

sketchybar --add bracket pill_clock clock \
	--set pill_clock \
	background.drawing=on \
	background.color=$PILL_COLOR \
	background.corner_radius=$PILL_RADIUS \
	background.border_width=1 \
	background.border_color=$PILL_BORDER \
	background.height=$PILL_HEIGHT

sketchybar --update
