#!/usr/bin/env bash

# A simple sketchybar config for aerospace users.
HELPER_DIR="$CONFIG_DIR/helpers"
PLUGIN_DIR="$CONFIG_DIR/plugins"
# shellcheck source=./helpers/executable_icon_map.sh
source "$HELPER_DIR/icon_map.sh"
# shellcheck source=./plugins/executable_colors.sh
source "$PLUGIN_DIR/colors.sh"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

bar=(
	blur_radius=20
	color="$TRANSPARENT"
	font_smoothing=on

	height=38
	position=top
)
sketchybar --bar "${bar[@]}"

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
	padding_left=5
	padding_right=5

	icon.color="$TEXT_WHITE"
	icon.font="VictorMono Nerd Font:Semibold:14.0"
	icon.padding_right=5

	label.color="$TEXT_WHITE"
	label.font="VictorMono Nerd Font:Semibold:14.0"

	updates=on
)
sketchybar --default "${default[@]}"

##### Adding AeroSpace Workspace Indicators #####
sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
	space=(
		drawing=off

		background.corner_radius=5
		background.height=24

		icon.font="sketchybar-app-font:Regular:14.0"
		icon.padding_right=15
		icon.y_offset=-1

		click_script="aerospace workspace $sid"
		script="$PLUGIN_DIR/aerospace.sh $sid"
	)
	sketchybar --add item space."$sid" left \
		--set space."$sid" "${space[@]}" \
		--subscribe space."$sid" aerospace_workspace_change
done

# Load icons on startup
for sid in $(aerospace list-workspaces --monitor=all --empty=no); do
	apps=$(aerospace list-windows --workspace "$sid" | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')

	sketchybar --set space."$sid" drawing=on

	icon_strip=""
	if [ "${apps}" != "" ]; then
		while read -r app; do
			__icon_map "$app"
			icon_strip+=" $icon_result"
		done <<<"${apps}"
	fi

	sketchybar --set space."$sid" icon="$icon_strip"
done

front_app=(
	# shellcheck source=./plugins/executable_front_app.sh
	script="$PLUGIN_DIR/front_app.sh"
)
sketchybar --add item front_app left \
	--set front_app "${front_app[@]}" \
	--subscribe front_app front_app_switched

space_separator=(
	drawing=off
	# shellcheck source=./plugins/executable_space_windows.sh
	script="$PLUGIN_DIR/space_windows.sh"
)
sketchybar --add item space_separator q \
	--set space_separator "${space_separator[@]}" \
	--subscribe space_separator aerospace_workspace_change space_windows_change front_app_switched

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
	--set clock update_freq=10 script="$PLUGIN_DIR/clock.sh" \
	\
	--add item battery right \
	--set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
	--subscribe battery system_woke power_source_change \
	\
	--add item wifi right \
	--set wifi script="$PLUGIN_DIR/wifi.sh" \
	--subscribe wifi wifi_change \
	\
	--add item volume right \
	--set volume script="$PLUGIN_DIR/volume.sh" \
	--subscribe volume volume_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
