#!/usr/bin/env bash

# A simple sketchybar config for aerospace users.
PLUGIN_DIR="$CONFIG_DIR/plugins"
# shellcheck source=./plugins/executable_colors.sh
source "$PLUGIN_DIR/colors.sh"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=37 color="$TRANSPARENT"

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
	padding_left=5
	padding_right=5
	icon.font="VictorMono Nerd Font:Bold:15.0"
	label.font="VictorMono Nerd Font:Semibold:14.0"
	icon.color="$TEXT_WHITE"
	label.color="$TEXT_WHITE"
	icon.padding_left=4
	icon.padding_right=4
	label.padding_left=4
	label.padding_right=4
	updates=on
	y_offset=-3
)
sketchybar --default "${default[@]}"

sketchybar --add item spacePaddingLeft left \
	--set spacePaddingLeft padding_left=-18

##### Adding AeroSpace Workspace Indicators #####
sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
	space=(
		background.corner_radius=5
		background.drawing=on
		background.height=23
		background.padding_left=5
		background.padding_right=5
		drawing=off
		icon="$sid"
		icon.padding_left=10
		icon.shadow.drawing=off
		label.font="sketchybar-app-font:Regular:14.0"
		label.padding_left=0
		label.padding_right=20
		label.shadow.drawing=off
		label.y_offset=-1
		click_script="aerospace workspace $sid"
		script="$CONFIG_DIR/plugins/aerospace.sh $sid"
	)
	sketchybar --add item space."$sid" left \
		--set space."$sid" "${space[@]}" \
		--subscribe space."$sid" aerospace_workspace_change
done

# Load icons on startup
for sid in $(aerospace list-workspaces --monitor 1 --empty no); do
	apps=$(aerospace list-windows --workspace "$sid" | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')

	sketchybar --set space."$sid" drawing=on

	icon_strip=" "
	if [ "${apps}" != "" ]; then
		while read -r app; do
			icon_strip+=" $("$CONFIG_DIR/plugins/icon_map_fn.sh" "$app")"
		done <<<"${apps}"
	else
		icon_strip=""
	fi
	sketchybar --set space."$sid" label="$icon_strip"
done

sketchybar --add item spacePaddingRight left \
	--set spacePaddingRight padding_left=-18

space_separator=(
	background.drawing=off
	icon.padding_left=20
	icon.padding_right=0
	label.drawing=off
	label.padding_left=0
	script="$PLUGIN_DIR/space_windows.sh"
)
sketchybar --add item space_separator q \
	--set space_separator "${space_separator[@]}" \
	--subscribe space_separator aerospace_workspace_change space_windows_change front_app_switched

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
	--set clock update_freq=10 icon= script="$PLUGIN_DIR/clock.sh" \
	\
	--add item battery right \
	--set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
	--subscribe battery system_woke power_source_change \
	\
	--add item wifi right \
	--set wifi script="$PLUGIN_DIR/wifi.sh" \
	--subscribe wifi wifi_change \
	\
	--add item volume right \
	--set volume script="$PLUGIN_DIR/volume.sh" \
	--subscribe volume volume_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
