#!/usr/bin/env zsh
export LESS='-fiFMRS -# 1 --follow-name --no-histdups'

# Homebrew
export HOMEBREW_BAT=1
export HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS=1
export HOMEBREW_CLEANUP_MAX_AGE_DAYS=1
export HOMEBREW_CURLRC=1
export HOMEBREW_DISPLAY_INSTALL_TIMES=1
export HOMEBREW_INSTALL_FROM_API=1
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_COMPAT=1
export HOMEBREW_NO_INSECURE_REDIRECT=1
export HOMEBREW_UPDATE_REPORT_ONLY_INSTALLED=1
export HOMEBREW_UPDATE_TO_TAG=1

# ptpython
export PYTHONSTARTUP="${HOME}/.pythonrc.py"
