indent_type               = 'Spaces'
indent_width              = 2
column_width              = 120
collapse_simple_statement = 'Always'
quote_style               = 'AutoPreferSingle'

sort_requires.enabled = true
