---
k9s:
  # Enable mouse support
  enableMouse: true

  # Hide K9s header
  headless: true

  # Hide K9s logo
  logoless: true

  # Don't check for the latest revision from the GitHub repository releases
  skipLatestRevCheck: true

  logger:
    # Go full screen while displaying logs
    fullScreenLogs: true

    # Whether to show timestamps in log lines
    showTime: true

  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
