---
k9s:
  enableMouse: true
  headless: true
  logoless: true
  skipLatestRevCheck: true

  shellPod:
    image: alpine:latest
    namespace: utility

  logger:
    fullScreenLogs: true
    showTime: true

  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
